### ISSUE TITLE
Loading pack file without dataKey does not work in 3.60.0-beta.7

### ISSUE THREAD

**Issue by robinheidrich** [phaserjs/phaser#6110]
## Version

* Phaser Version: Phaser v3.60.0-beta.7

* Operating system: Windows 11

* Browser: Google Chrome 101.0.4951.54

## Description

According to the [docs](https://photonstorm.github.io/phaser3-docs/Phaser.Loader.LoaderPlugin.html#pack__anchor) it is optional to specify a data key and in previous versions it worked without ([see here](https://labs.phaser.io/edit.html?src=src/loader/file%20pack/load%20file%20pack.js), remove the data key). Since the latest beta it does not work anymore and gives the following error:

```
Uncaught TypeError: key.indexOf is not a function
    at GetValue (phaser.js:221626:18)
    at p.addPack (phaser.js:108331:27)
```

## Example Test Code

In this [example](https://labs.phaser.io/edit.html?src=src/loader/file%20pack/load%20file%20pack.js&v=dev), remove the data key from the pack load.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
