### ISSUE TITLE
Graphics inside a Container bugs out since v3.60

### ISSUE THREAD

**Issue by Antriel** [phaserjs/phaser#6093]
## Version
v3.60.0-beta.6

## Description
`ctx.save is not a function` in `GraphicsCanvasRenderer`.

Happens in Canvas mode when Graphics object is inside a container. Worked in v3.55.

## Example Test Code

```js
var config = {
    type: Phaser.CANVAS,
    scene: {
        create: create
    }
};

var game = new Phaser.Game(config);

function create () {
    var graphics = this.add.graphics();
    graphics.strokeCircle(0, 0, 60);
    var container = this.add.container(0, 0, [ graphics ]);
}
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
